@baseUrl = http://localhost:4000

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "12345678"
}

###

# @name login
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "12345678"
}
