version: '3.8'

services:
  sql-db:
    image: postgres:16.1
    ports: 
      - 5432:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: api-nest-dev
      PGDATA: /var/lib/postgresql/data
    